lms/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

admin.site.index_title = 'Unstarted Administration'
admin.site.site_header = 'Unstarted Administration'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
    path('management/', include('manager.urls')),
    path('teacher/', include('teacher.urls')),
    path('student/', include('student.urls')),
    path('payment/', include('payment.urls')),
    path('ckeditor', include('ckeditor_uploader.urls')),
]

urlpatterns += static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL , document_root = settings.STATIC_ROOT)

student/urls.py
from django.urls import path
from .views import (
    index,
    enrolled_courses,
    course_detail_view,
    course_units_view,
    allcourses,
    calender,
    communication,
    course_detail,
    course_learning,
    course_tools,
    notifications_page,
    course_content,
    assignments,
    assignments_detail,
    course_tasks,
    unit_launch
)


app_name = 'student'


urlpatterns = [
    path('', index, name='home'),
    path('courses/', enrolled_courses, name='enrolled-courses'),
    path('course/<int:course_id>/', course_detail_view, name='course-detail'),
    path('course/<int:course_id>/units/', course_units_view, name='course-units-view'),
    path('courses/allcourses',allcourses,name="allcourses"),
    path('courses/calender',calender,name="calender"),
    path('courses/communication',communication,name="communication"),
    path('courses/course_learning',course_learning,name="course_learning"),
    path('courses/course_tools',course_tools,name="course_tools"),
    path('courses/notifications_page',notifications_page,name="notifications"),
    path('courses/course_content',course_content,name="course_content"),
    path('courses/assignments',assignments,name="assignments"),
    path('courses/assignments_detail',assignments_detail,name="assignments_detail"),
    path('courses/course_tasks',course_tasks,name="course_tasks"),
    path('courses/unit_launch',unit_launch,name="unit_launch"),
]

student/models.py
from django.db import models

# Create your models here.

student/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from teacher.models import (
    Enrollment,
    Course,
    LessonProgress,
)
from django.utils import timezone

@login_required
def enrolled_courses(request):
    enrolled_courses = Enrollment.objects.filter(student=request.user).select_related('course')
    return render(request, 'student/enrolled_courses.html', {'enrolled_courses': enrolled_courses})


@login_required
def course_detail_view(request, course_id):
    course = get_object_or_404(Course, pk=course_id)
    student = request.user
    enrollment = Enrollment.objects.filter(student=student, course=course).first()
    # Update the last_accessed field to the current timestamp
    enrollment.last_accessed = timezone.now()
    enrollment.save()
    units = course.unit_set.all()

    unit_progress = []
    for unit in units:
        lessons_total = unit.lesson_set.count()
        lessons_completed = LessonProgress.objects.filter(enrollment=enrollment, lesson__unit=unit, is_completed=True).count()
        completion_percentage = (lessons_completed / lessons_total) * 100 if lessons_total > 0 else 0
        unit_progress.append((unit, completion_percentage, lessons_completed, lessons_total))

    context = {
        'course': course,
        'enrollment': enrollment,
        'unit_progress': unit_progress,
    }

    return render(request, 'student/course_detail.html', context)



def course_units_view(request, course_id):
    course = get_object_or_404(Course, pk=course_id)
    units = course.unit_set.all()

    for unit in units:
        unit.lessons = unit.lesson_set.all()

    context = {
        'course': course,
        'units': units,
    }

    return render(request, 'student/course_learning_page.html', context)


def index(request):
    total_course_enrollments = Enrollment.objects.filter(student=request.user).select_related('course').order_by('-last_accessed')
    recently_accessed_course_enrollments = total_course_enrollments[:6]
    total_course_enrollments_count = total_course_enrollments.count()

    context = {
        'recently_accessed_course_enrollments' : recently_accessed_course_enrollments,
        'total_course_enrollments_count' : total_course_enrollments_count
    }
    return render(request, 'student/index.html', context)


def allcourses(request):
    return render(request,'student/enrolled_courses.html')

def calender(request):
    return render(request,'student/calender_page.html')

def communication(request):
    return render(request,'student/communication_page.html')

def course_detail(request):
    return render(request,'student/course_detail.html')

def course_learning(request):
    return render(request,'student/course_learning_page.html')

def course_tools(request):
    return render(request,'student/course_tools_page.html')

def notifications_page(request):
    return render(request,'student/notifications_page.html')

def course_content(request):
    return render(request,'student/course_learning_page.html')

def assignments(request):
    return render(request,'student/assignments.html')

def assignments_detail(request):
    return render(request,'student/assignments_detail.html')

def course_tasks(request):
    return render(request,'student/course_tasks.html')

def unit_launch(request):
    return render(request,'student/unit_launch.html')

templates/student/assignments.html
{% extends 'student/base2.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Course Content{% endblock title %}
{% block css %}
<link rel="stylesheet" href="{% static "styles/student/test_and_assignments_style.css"%}">
<link href='https://unpkg.com/boxicons@2.1.1/css/boxicons.min.css' rel='stylesheet'>
{% endblock css %}
{% block google_tags %}
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-YTXLDDT540"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-YTXLDDT540');
</script>
{% endblock google_tags %}
{% block body %}
        <section class="home">
            <div class="test-assignment-tab">
                <nav class="nav-bar">
                    <ul class="ta-tabs">
                        <li class="tab-item"><a href="#test-item" class="active" onclick="return false">Tests</a></li>
                        <li class="tab-item"><a href="#assignment-item" onclick="return false">Assignments</a></li>
                    </ul>
                </nav>
            </div>

            <div class="wrapper_tab-content">
                <section id="test-item" class="tab-content content-visible">
                    <div class="ta-list">
                        <div class="ta-card">
                            <img
                                src="http://www.sulitest.org/files/source/logo%20test%20horiz%20bis.png?1574185700651">
                            <div class="details">
                                <a href="{%url 'student:assignments_detail'%}">Test - 1</a>
                                <p>Time: 1hr 30min</p>
                            </div>
                        </div>

                        <div class="ta-card">
                            <img
                                src="http://www.sulitest.org/files/source/logo%20test%20horiz%20bis.png?1574185700651">
                            <div class="details">
                                <a href="{%url 'student:assignments_detail'%}">Test - 2</a>
                                <p>Time: 1hr 30min</p>
                            </div>
                        </div>

                        <div class="ta-card">
                            <img
                                src="http://www.sulitest.org/files/source/logo%20test%20horiz%20bis.png?1574185700651">
                            <div class="details">
                                <a href="{%url 'student:assignments_detail'%}">Test - 3</a>
                                <p>Time: 1hr 30min</p>
                            </div>
                        </div>

                        <div class="ta-card">
                            <img
                                src="http://www.sulitest.org/files/source/logo%20test%20horiz%20bis.png?1574185700651">
                            <div class="details">
                                <a href="{%url 'student:assignments_detail'%}">Test - 4</a>
                                <p>Time: 1hr 30min</p>
                            </div>
                        </div>

                        <div class="ta-card">
                            <img
                                src="http://www.sulitest.org/files/source/logo%20test%20horiz%20bis.png?1574185700651">
                            <div class="details">
                                <a href="{%url 'student:assignments_detail'%}">Test - 5</a>
                                <p>Time: 1hr 30min</p>
                            </div>
                        </div>

                        <div class="ta-card">
                            <img
                                src="http://www.sulitest.org/files/source/logo%20test%20horiz%20bis.png?1574185700651">
                            <div class="details">
                                <a href="{%url 'student:assignments_detail'%}">Test - 6</a>
                                <p>Time: 1hr 30min</p>
                            </div>
                        </div>
                    </div>
                </section>

                <section id="assignment-item" class="tab-content">
                    <div class="ta-list">
                        <div class="ta-card">
                            <img
                                src="https://t4.ftcdn.net/jpg/04/02/42/69/360_F_402426919_8EQoxyOoC1QMZE8a9X0l0IAsjzjrZpWX.jpg">
                            <div class="details">
                                <a href="{%url 'student:assignments_detail'%}">Assignment - 1</a>
                                <p>Time: 1hr 30min</p>
                            </div>
                        </div>

                        <div class="ta-card">
                            <img
                                src="https://t4.ftcdn.net/jpg/04/02/42/69/360_F_402426919_8EQoxyOoC1QMZE8a9X0l0IAsjzjrZpWX.jpg">
                            <div class="details">
                                <a href="{%url 'student:assignments_detail'%}">Assignment - 2</a>
                                <p>Time: 1hr 30min</p>
                            </div>
                        </div>

                        <div class="ta-card">
                            <img
                                src="https://t4.ftcdn.net/jpg/04/02/42/69/360_F_402426919_8EQoxyOoC1QMZE8a9X0l0IAsjzjrZpWX.jpg">
                            <div class="details">
                                <a href="{%url 'student:assignments_detail'%}">Assignment - 3</a>
                                <p>Time: 1hr 30min</p>
                            </div>
                        </div>

                        <div class="ta-card">
                            <img
                                src="https://t4.ftcdn.net/jpg/04/02/42/69/360_F_402426919_8EQoxyOoC1QMZE8a9X0l0IAsjzjrZpWX.jpg">
                            <div class="details">
                                <a href="{%url 'student:assignments_detail'%}">Assignment - 4</a>
                                <p>Time: 1hr 30min</p>
                            </div>
                        </div>

                    </div>
                </section>
            </div>
        </section>

    </div>
    {% block script %}
    <script src="js/test_assignments.js"></script>
    {% endblock script %}
    {% endblock body %}

templates/student/assignments_detail.html
{% extends 'student/base2.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Course Content{% endblock title %}
{% block css %}
<link rel="stylesheet" href="{% static "styles/student/ta_submission_style.css"%}">
<link href='https://unpkg.com/boxicons@2.1.1/css/boxicons.min.css' rel='stylesheet'>
{% endblock css %}
{% block google_tags %}
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-YTXLDDT540"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-YTXLDDT540');
</script>
{% endblock google_tags %}
{% block body %}

        <section class="home">
           <div class="main-content">
                <div class="title-section">
                    <h1 class="ta-title">Test - 1</h1>
                    <div class="ta-details">
                        <img src="images/fileImgPDF.png" alt="file name" class="ta-file-type-img">
                        <a href="Test And Assigments Files/sample.pdf" download="sample File" class="file-download-link">Test File.pdf</a>
                        <p class="date-time">5th Dec 2022, 10:45 AM</p>
                    </div>
                    <h1 class="ta-submission-status">Submission Status</h1>
                </div>

                <div class="submission-section">
                    <table class="submission-details-table">
                        <tr>
                            <td class="c1">Submission Status</td>
                            <td class="c2 ta-sub-status-val">Submitted for grading</td>
                        </tr>
                        <tr>
                            <td class="c1">Grading Status</td>
                            <td class="c2 ta-grad-status-val" style="background: #d5ffcf;">Released</td>
                        </tr>
                        <tr>
                            <td class="c1">Last Modified</td>
                            <td class="c2 ta-last-modified-val">Tuesday, 5 April 2022, 5:55 PM</td>
                        </tr>
                        <tr>
                            <td class="c1">File Submissions</td>
                            <td class="c2 ta-file-sub-val">
                                <div class="file-info">
                                    <img src="images/fileImgPDF.png" alt="file type" class="ta-file-type-img">
                                    <a href="Test And Assigments Files/sample.pdf" download="sample File" class="file-download-link">DocScanner 5 April 2022 2 - 18 PM. pdf</a>
                                    <p>5 April 2022, 8:44 PM</p>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td class="c1">Submission Comments</td>
                            <td class="c2 ta-sub-comments">
                                <div class="comments-section">
                                    <i class="fa-sharp fa-solid fa-caret-right"></i>
                                    <p>Comments (<span>0</span>)</p>
                                </div>
                            </td>
                        </tr>
                    </table>

                    <div class="edit-remove-sub-buttons">
                        <div class="sub-buttons">
                            <button class="edit btn">EDIT SUBMISSION</button>
                            <button class="remove btn">REMOVE SUBMISSION</button>
                        </div>
                        <p>You can still make changes to your submission.</p>
                    </div>
                </div>

                <div class="feedback-section">
                    <h1>Feedback</h1>
                    <table class="grade-details-table">
                        <tr>
                            <td class="c1">Grade</td>
                            <td class="c2 ta-grade-val">26.00 / 30.00</td>
                        </tr>
                        <tr>
                            <td class="c1">Graded On</td>
                            <td class="c2 ta-graded-time-val">Sunday, 27 April 2022, 4:00 PM</td>
                        </tr>
                        <tr>
                            <td class="c1">Graded By</td>
                            <td class="c2 ta-graded-By-val">
                                <img src="images/User.png" alt="Professor name">
                                <p>Mr. David Hopper</p>
                            </td>
                        </tr>
                    </table>
                </div>
           </div>
        </section>
    </div>
    {% endblock body %}

templates/student/base.html
{%load static%}
<!DOCTYPE html>
<html lang="en">


<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static "styles/student/all.css" %}">
    <link rel="stylesheet" href="{% static "styles/student/style.css" %}">
    <!----===== Boxicons CSS ===== -->
    <link href='https://unpkg.com/boxicons@2.1.1/css/boxicons.min.css' rel='stylesheet'>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" rel="stylesheet">
    <title>{% block title %}{% endblock title %}</title>
    {% block css %}
    {% endblock css %}
    {% block google_tags %}{% endblock google_tags %}
</head>

<body>
    <header class="header">
        <div class="left-header">
            <div class="menu-toggle" id="mobile-menu">
                <span class="bar"></span>
                <span class="bar"></span>
                <span class="bar"></span>
            </div>
            <img id="logo" src="{% static "images/logoblue.png"%}">
        </div>

        <div class="right-header">
            <div class="all-apps-container">
                <div class="right-header-icons">
                    <img class="all-apps-icon icon" src="{% static "images/Apps.png"%}">
                </div>
            </div>

            <div class="notification-container">
                <div class="right-header-icons">
                    <img class="notify-icon icon" src="{% static "images/notification.png"%}">
                </div>
                <div class="dropdown">
                    {% for noti in notification %}
                    <div class="notify_item">

                        <div class="notify_img">
                            <img src={{noti.user.profile.profile_pic.url}} alt="profile_pic" style="width: 50px">
                        </div>

                        <div class="notify_info">
                            <p>{{noti.notification}}<span></span></p>
                            <button class="notify-btn">Explore All</button>
                        </div>
                        <div class="notify_time">
                            <p>{{noti.created_at}}</p>
                            <h1>...</h1>
                        </div>
                    </div>
                    {% endfor %}

                    <div class="notify_See_All">
                        <button class="see-All">See All Notifications</button>
                    </div>
                </div>
            </div>

            <div class="profile-container">
                <div class="right-header-icons">
                    <img class="profile-icon icon" src="{{request.user.profile.profile_pic.url}}">
                </div>
                <div class="dropdown-content">
                    <p style="color:black;font-weight:bolder;padding-left:20px;font-size:13px;padding-top:20px;">username : {{request.user.username}}</p>
                    <a href="#"><span><i class="fa-solid fa-gauge"></i>Settings</span></a>
                    <a href="#"><span><i class="fa-solid fa-table"></i>Grades</span></a>
                    <a href="#"><span><i class="fa-solid fa-comment"></i>Messages</span></a>
                    <a href="#"><span><i class="fa-solid fa-wrench"></i>History</span></a>
                    <a href="{%url 'logout'%}"><span><i class="fa-solid fa-arrow-right-from-bracket"></i>Logout</span></a>
                </div>
            </div>
        </div>
    </header>

    <div class="content-container">
        <nav class="sidebar close">
            <header>
                <i class='bx bx-chevron-right toggle'></i>
            </header>

            <div class="menu-bar">
                <div class="menu">
                    <ul class="menu-links">
                        <li class="nav-link">
                            <a class="active" href="{%url 'student:home'%}">
                                <i class='bx bx-home-alt icon'></i>
                                <span class="text nav-text">Dashboard</span>
                            </a>
                        </li>

                        <li class="nav-link">
                            <a href="{%url 'student:enrolled-courses'%}">
                                <i class='bx bx-bar-chart-alt-2 icon'></i>
                                <span class="text nav-text">All courses</span>
                            </a>


                        </li>

                        <li class="nav-link">
                            <a href="{%url 'student:calender'%}">
                                <i class='bx bx-bell icon'></i>
                                <span class="text nav-text">Calender</span>
                            </a>
                        </li>

                        <li class="nav-link">
                            <a href="{%url 'student:notifications'%}">
                                <i class='bx bx-pie-chart-alt icon'></i>
                                <span class="text nav-text">Notifications</span>
                            </a>
                        </li>

                        <li class="nav-link">
                            <a href="yourFiles_page.html">
                                <i class='bx bx-heart icon'></i>
                                <span class="text nav-text">Your Files</span>
                            </a>
                        </li>

                        <li class="nav-link">
                            <a href="events_page.html">
                                <i class='bx bx-wallet icon'></i>
                                <span class="text nav-text">Events</span>
                            </a>
                        </li>

                        <li  class="nav-link">

                            <a href="#">
                                <i class='bx bx-mail-send icon'></i>
                                <span class="text nav-text">contact</span>
                            </a>
                        </li>
                </div>

                <div class="bottom-content">
                    <li class="">
                        <a href="#">
                            <i class='bx bx-log-out icon'></i>
                            <span class="text nav-text">Logout</span>
                        </a>

                    </li>
                </div>
            </div>
        </nav>

        {% block body %}
        {% endblock body %}


        {% block script %}
        {% endblock script %}
        <script src="{% static "styles/student/app.js"%}"></script>
    </body>
    </html>

templates/student/base2.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static "styles/student/all.css"%}">
    <link href='https://unpkg.com/boxicons@2.1.1/css/boxicons.min.css' rel='stylesheet'>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" rel="stylesheet">
    <!----===== Boxicons CSS ===== -->
    <link href='https://unpkg.com/boxicons@2.1.1/css/boxicons.min.css' rel='stylesheet'>
    <title>{% block title %}{% endblock title %}</title>
    {% block css %}
    {% endblock css %}
    {% block google_tags %}{% endblock google_tags %}
</head>
<body>
    <header class="header">
        <div class="first-header">
            <div class="left-header">
                <div class="menu-toggle" id="mobile-menu">
                    <span class="bar"></span>
                    <span class="bar"></span>
                    <span class="bar"></span>
                </div>

                <img id="logo" src="{% static "images/logoblue.png"%}">
            </div>

            <div class="right-header">
                <div class="all-apps-container">
                    <div class="right-header-icons">
                        <img class="all-apps-icon icon" src="{% static "images/Apps.png"%}">
                    </div>
                </div>

                <div class="notification-container">
                    <div class="right-header-icons">
                        <img class="notify-icon icon" src="{% static "images/notification.png"%}">
                    </div>
                    <div class="dropdown">
                        {% for noti in notification %}
                    <div class="notify_item">

                        <div class="notify_img">
                            <img src={{noti.user.profile.profile_pic.url}} alt="profile_pic" style="width: 50px">
                        </div>

                        <div class="notify_info">
                            <p>{{noti.notification}}<span></span></p>
                            <button class="notify-btn">Explore All</button>
                        </div>
                        <div class="notify_time">
                            <p>{{noti.created_at}}</p>
                            <h1>...</h1>
                        </div>
                    </div>
                    {% endfor %}

                        <div class="notify_See_All">
                            <button class="see-All">See All Notifications</button>
                        </div>
                    </div>
                </div>

                <div class="profile-container">
                    <div class="right-header-icons">
                        <img class="profile-icon icon" src="{{request.user.profile.profile_pic.url}}">
                    </div>
                    <div class="dropdown-content">
                        <p style="color:black;font-weight:bolder;padding-left:20px;font-size:13px;padding-top:20px;">username : {{request.user.username}}</p>
                        <a href="#"><span><i class="fa-solid fa-gauge"></i>Settings</span></a>
                        <a href="#"><span><i class="fa-solid fa-table"></i>Grades</span></a>
                        <a href="#"><span><i class="fa-solid fa-comment"></i>Messages</span></a>
                        <a href="#"><span><i class="fa-solid fa-wrench"></i>Preferences</span></a>
                        <a href="{%url 'logout'%}"><span><i class="fa-solid fa-arrow-right-from-bracket"></i>Logout</span></a>
                    </div>
                </div>
            </div>
        </div>

        <div class="second-header">
            <nav class="nav-bar">
                <ul class="navigation">
                    <li><a href="" class="first active">Course Home</a></li>
                    <li><a href="{%url 'student:course_content'%}">Content</a></li>
                    <li><a href="{%url 'student:assignments'%}">Test & Assignments</a></li>
                    <li><a href="communication_page.html">Communication</a></li>
                    <li><a href="{%url 'student:course_tools'%}">Course Tools</a></li>
                    <li><a href="{%url 'student:course_tasks'%}">Course Tasks</a></li>
                </ul>
            </nav>
        </div>
    </header>

    <div class="content-container">
        <nav class="sidebar close">
            <header>
                <i class='bx bx-chevron-right toggle'></i>
            </header>

            <div class="menu-bar">
                <div class="menu">
                    <ul class="menu-links">
                        <li class="nav-link">
                            <a href="index.html">
                                <i class='bx bx-home-alt icon' ></i>
                                <span class="text nav-text">Dashboard</span>
                            </a>
                        </li>

                        <li class="nav-link">
                            <a href="all_courses_page.html">
                                <i class='bx bx-bar-chart-alt-2 icon' ></i>
                                <span class="text nav-text">All courses</span>
                            </a>


                        </li>

                        <li class="nav-link">
                            <a href="calender_page.html">
                                <i class='bx bx-bell icon'></i>
                                <span class="text nav-text">Calender</span>
                            </a>
                        </li>

                        <li class="nav-link">
                            <a href="notifications_page.html">
                                <i class='bx bx-pie-chart-alt icon' ></i>
                                <span class="text nav-text">Notifications</span>
                            </a>
                        </li>

                        <li class="nav-link">
                            <a href="yourFiles_page.html">
                                <i class='bx bx-heart icon' ></i>
                                <span class="text nav-text">Your Files</span>
                            </a>
                        </li>

                        <li class="nav-link">
                            <a href="events_page.html">
                                <i class='bx bx-wallet icon' ></i>
                                <span class="text nav-text">Events</span>
                            </a>
                        </li>

                    </ul>
                </div>

                <div class="bottom-content">
                    <li class="">
                        <a href="#">
                            <i class='bx bx-log-out icon' ></i>
                            <span class="text nav-text">Logout</span>
                        </a>
                    </li>

                    <li class="mode">
                        <div class="sun-moon">
                            <i class='bx bx-moon icon moon'></i>
                            <i class='bx bx-sun icon sun'></i>
                        </div>
                        <span class="mode-text text">Dark mode</span>

                        <div class="toggle-switch">
                            <span class="switch"></span>
                        </div>
                    </li>

                </div>
            </div>
        </nav>


        {% block body %}
        {% endblock body %}


        {% block script %}
        {% endblock script %}

        <script src="{% static "styles/student/app.js"%}"></script>
        <script src="{% static "styles/student/course_detail.js"%}"></script>
    </body>
    </html>