lms/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

admin.site.index_title = 'Unstarted Administration'
admin.site.site_header = 'Unstarted Administration'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
    path('management/', include('manager.urls')),
    path('teacher/', include('teacher.urls')),
    path('student/', include('student.urls')),
    path('payment/', include('payment.urls')),
    path('ckeditor', include('ckeditor_uploader.urls')),
]

urlpatterns += static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL , document_root = settings.STATIC_ROOT)

manager/urls.py
from django.urls import path
from . import views

app_name = 'manager'
urlpatterns = [
    path('home/', views.manager_home, name='home'),
    path('requests/<str:status>/<int:pk>/', views.application_details, name='application-details'),

    path('announcements/', views.AnnouncementListView.as_view(), name='announcement-list'),
    path('announcements/create/', views.AnnouncementCreateView.as_view(), name='announcement-create'),
    path('announcements/<int:pk>/update/', views.AnnouncementUpdateView.as_view(), name='announcement-update'),
    path('announcements/<int:pk>/statusupdate/', views.AnnouncementStatusUpdateView, name='announcement-status-update'),
    path('announcements/<int:pk>/', views.AnnouncementDetailView.as_view(), name='announcement-detail'),
    path('announcements/<int:pk>/add-link/', views.announcement_add_link, name='announcement-add-link'),
    path('announcements/<int:pk>/delete_link/<int:link_pk>/', views.announcement_delete_link, name='announcement-delete-link'),
    path('announcements/<int:pk>/add-file/', views.announcement_add_file, name='announcement-add-file'),
    path('announcements/<int:pk>/delete_file/<int:file_pk>/', views.announcement_delete_file, name='announcement-delete-file'),

    path('events/', views.EventsListView.as_view(), name='events-list'),
    path('events/create/', views.EventsCreateView.as_view(), name='events-create'),
    path('events/<int:pk>/update/', views.EventsUpdateView.as_view(), name='events-update'),
    path('events/<int:pk>/statusupdate/', views.EventsStatusUpdateView, name='events-status-update'),
    path('events/<int:pk>/', views.EventsDetailView.as_view(), name='events-detail'),
    path('events/<int:pk>/add-link/', views.events_add_link, name='events-add-link'),
    path('events/<int:pk>/delete_link/<int:link_pk>/', views.events_delete_link, name='events-delete-link'),
    path('events/<int:pk>/add-file/', views.events_add_file, name='events-add-file'),
    path('events/<int:pk>/delete_file/<int:file_pk>/', views.events_delete_file, name='events-delete-file'),


    path('students/', views.StudentProfileListView.as_view(), name='student-profile-list'),
    path('teachers/', views.TeacherProfileListView.as_view(), name='teacher-profile-list'),
    path('managers/', views.ManagerProfileListView.as_view(), name='manager-profile-list'),
    path('student/<int:pk>/', views.StudentProfileDetailView.as_view(), name='student-profile-detail'),
    path('teacher/<int:pk>/', views.TeacherProfileDetailView.as_view(), name='teacher-profile-detail'),
    path('manager/<int:pk>/', views.ManagerProfileDetailView.as_view(), name='manager-profile-detail'),



    path('contact/', views.contact, name='contact'),
    # path('events/', views.manager_event, name='events'),
]

manager/models.py
from django.db import models
from account.models import *
from django.utils import timezone
from django.contrib.auth.models import User
from django.utils.text import slugify
import hashlib
# Create your models here.

def get_unique_string(body, time):
    s = str(body)+str(time)
    result_str = hashlib.sha1(s.encode()).hexdigest()[:10]
    return result_str

class Announcement(models.Model):

    DRAFT = 'draft'
    RELEASED = 'released'
    STATUS_CHOICES = [
        (DRAFT, 'Draft'),
        (RELEASED, 'Released'),
    ]

    user_profile = models.ForeignKey(Profile,on_delete=models.CASCADE)
    title = models.CharField(max_length=50,blank=True,null=True)
    description = models.TextField()
    created_at = models.DateTimeField(default=timezone.now)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default=DRAFT)

    slug = models.SlugField(max_length=16, null=True, unique=True, editable=False)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        super(Announcement, self).save()
        self.slug = slugify(get_unique_string(self.title,self.user_profile))
        super(Announcement, self).save()


class AnnouncementFile(models.Model):
    announcement = models.ForeignKey(Announcement, on_delete=models.CASCADE)
    file = models.FileField(upload_to='announcement_files/')


class AnnouncementLink(models.Model):
    announcement = models.ForeignKey(Announcement, on_delete=models.CASCADE)
    link = models.URLField()


class Events(models.Model):

    DRAFT = 'draft'
    RELEASED = 'released'
    STATUS_CHOICES = [
        (DRAFT, 'Draft'),
        (RELEASED, 'Released'),
    ]

    user_profile = models.ForeignKey(Profile,on_delete=models.CASCADE)
    title= models.CharField(max_length=50,blank=True,null=True)
    description = models.CharField(max_length=200,blank=True,null=True)
    created_at = models.DateTimeField(default=timezone.now)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default=DRAFT)

    slug = models.SlugField(max_length=16, null=True, unique=True, editable=False)

    def __str__(self):
        return self.title[0:15]

    def save(self, *args, **kwargs):
        super(Events, self).save()
        self.slug = slugify(get_unique_string(self.description,self.user))
        super(Events, self).save()

class EventsFile(models.Model):
    announcement = models.ForeignKey(Events, on_delete=models.CASCADE)
    file = models.FileField(upload_to='event_files/')


class EventsLink(models.Model):
    announcement = models.ForeignKey(Events, on_delete=models.CASCADE)
    link = models.URLField()

class news(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    title= models.CharField(max_length=50,blank=True,null=True)
    description = models.CharField(max_length=200,blank=True,null=True)
    created_at = models.DateTimeField()

    slug = models.SlugField(max_length=16, null=True, unique=True, editable=False)

    def __str__(self):
        return self.announcement[0:15]

    def save(self, *args, **kwargs):
        super(news, self).save()
        self.slug = slugify(get_unique_string(self.description,self.user))
        super(news, self).save()

class mainwebsite(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    header = models.CharField(max_length=200,blank=True,null=True)
    footer = models.CharField(max_length=200,blank=True,null=True)
    created_at = models.DateTimeField()

    def __str__(self):
        return self.user.username

class testimonials(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    image = models.CharField(max_length=200,blank=True,null=True)
    content = models.CharField(max_length=200,blank=True,null=True)
    created_at = models.DateTimeField()

    slug = models.SlugField(max_length=16, null=True, unique=True, editable=False)

    def __str__(self):
        return self.content[0:15]

    def save(self, *args, **kwargs):
        super(testimonials, self).save()
        self.slug = slugify(get_unique_string(self.content,self.user))
        super(testimonials, self).save()

class mainpagenews(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    image = models.CharField(max_length=200,blank=True,null=True)
    content = models.CharField(max_length=200,blank=True,null=True)
    created_at = models.DateTimeField()

    slug = models.SlugField(max_length=16, null=True, unique=True, editable=False)

    def __str__(self):
        return self.content[0:15]

    def save(self, *args, **kwargs):
        super(mainpagenews, self).save()
        self.slug = slugify(get_unique_string(self.content,self.user))
        super(mainpagenews, self).save()

class Contact(models.Model):
    name = models.CharField(max_length=200)
    email = models.EmailField()
    msg = models.TextField()
    def __str__(self):
        return 'Msg from '+self.name

templates/manager/announcement_detail.html
{% extends 'manager/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Announcements{% endblock title %}
{% block css %}
<link rel="stylesheet" href="{% static 'styles/announcements-style.css'%}">
<link rel="stylesheet" href="{% static 'styles/add-popup.css'%}">
<link rel="stylesheet" href="{% static 'css/w3.css' %}">
<style>
        p {
            margin-bottom: 0 !important;
        }

        .leftP {
            background-image: radial-gradient(circle farthest-corner at 10% 20%, rgb(162, 88, 253) 0%, rgba(116, 182, 247, 1) 90%);
            display: flex;
            align-items: center;
            justify-content: center;
        }

        *:focus {
            box-shadow: none !important;
        }

        @media(max-width:1000px) {
            .leftP {
                width: 100% !important;
            }

            .rightP {
                width: 100% !important;
            }
        }
</style>
{% endblock css %}
{% block body %}


    <div class="body">


        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
            <strong>Message!-</strong> {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% endfor %}
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="/" style="color:initial">Home</a></li>
                <li class="breadcrumb-item"><a href="/" style="color:initial">Announcements</a></li>
            <li class="breadcrumb-item active" aria-current="page">Name</li>
            </ol>
        </nav>

        <div class="view-container">
            <div class="view">
                <div class="heading view-item">
                    <div class="head heading-item">
                        <p class="heading-name">
                            {{ announcement.title }}
                        </p>
                    </div>
                    <div class="release-edit heading-item">
                        <div class="release">
                            <form method="post" action="{% url 'manager:announcement-status-update' announcement.id %}">
                                {% csrf_token %}
                                {% if announcement.status == 'draft' %}
                                <button class="release-btn" type="submit">
                                    <img src="{%static 'rsc/icons8-telegram-app-30.png'%}" alt="" class="icon">
                                    <p>Release</p>
                                </button>
                                {% elif announcement.status == 'released' %}
                                <button class="release-btn" type="submit">
                                    <img src="{%static 'rsc/icons8-draft-48.png'%}" alt="" class="icon">
                                    <p>Draft</p>
                                </button>
                                {% endif %}
                            </form>


                        </div>
                        <div class="edit">
                            <button class="edit-btn" type="button" data-toggle="modal" data-target="#exampleModal">
                                <img src="{% static 'rsc/icons8-edit-26.png' %}" alt="" class="icon">
                                <p>Edit</p>
                            </button>
                        </div>
                    </div>
                </div>
                <div class="announcement view-item">
                    <p>{{ announcement.description }}</p>

                </div>
                <div class=" view-item">
                    <div class="heading links-item">
                        <div class="head heading-item">
                            <p class="heading-name">
                                Links
                            </p>
                        </div>
                        <div class="add-item heading-item">
                            <div class="add">
                                <button class="add-btn" data-toggle="modal" data-target="#addLink">
                                    <p>Add +</p>
                                </button>
                            </div>
                        </div>
                    </div>
                    <div class="links-item">
                        <ol class="links-list">
                            <li class="link">
                                {% for link in object.announcementlink_set.all %}
                                <div>
                                    <span class="link-name"><a href="{{ link.link }}">{{ link.link }}</a></span>
                                    <span>
                                        <a href="{% url 'manager:announcement-delete-link' pk=announcement.pk link_pk=link.pk %}">
                                            <img src="{% static 'rsc/icons8-delete-24 (1).png' %}" alt="" class="dustbin mx-2 my-0">
                                        </a>
                                    </span>


                                {% empty %}
                                <span>No links available</span>
                                {% endfor %}
                            </div>

                            </li>

                        </ol>
                    </div>
                </div>
                <div class=" view-item">
                    <div class="heading docs-item">
                        <div class="head heading-item">
                            <p class="heading-name">
                                Files
                            </p>
                        </div>
                        <div class="add-item heading-item">
                            <div class="add">
                                <button class="add-btn" data-toggle="modal" data-target="#addFile">
                                    <p>Add +</p>
                                </button>
                            </div>
                        </div>
                    </div>
                    <div class="docs-item">
                        <ol class="links-list">
                            <li class="link">
                                {% for file in object.announcementfile_set.all %}
                                <div>
                                    <span class="link-name"><a href="{{ file.file.url }}">{{ file.file.name }}</a></span>
                                    <span><a href="{% url 'manager:announcement-delete-file' file_pk=file.pk pk=announcement.pk %}"><img src="{% static 'rsc/icons8-delete-24 (1).png' %}" alt=""
                                        class="dustbin mx-2 my-0"></a></span>
                                    {% empty %}
                                    <span>No files available</span>
                                    {% endfor %}
                                </div>


                            </li>

                        </ol>
                    </div>
                </div>
            </div>
        </div>

    </div>
    </div>

    <!-- edit popup -->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
            <div class="modal-content">
                <div class="d-flex flex-wrap-reverse">

                    <div class="leftP w-50" style="min-height:400px ;">
                        <div class="left-cont">
                            <img src="{% static 'rsc/icons8-project-management-48.png' %}" alt="">
                            <h3>managesnap</h3>
                        </div>

                    </div>
                    <div class="rightP px-4 w-50 my-2">

                        <h5 class="modal-title py-3" id="exampleModalLabel">Edit Announcement</h5>
                        <form action="{% url 'manager:announcement-update' announcement.pk %}" method="post">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="title">Title</label>
                                <input type="text" class="form-control w-100" id="title" name="title" value="{{ announcement.title }}">
                            </div>
                            <div class="form-group">
                                <label for="desc">Description</label>
                                <textarea class="form-control w-100" id="desc" rows="3" name="description">{{ announcement.description }}</textarea>
                            </div>
                            <div class="footer-btns mt-5">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                <button type="submit" class="btn btn-primary">Save changes</button>
                            </div>
                        </form>




                    </div>

                </div>

            </div>
        </div>
    </div>

    <!-- add link popup -->
    <div class="modal fade" id="addLink" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
            <div class="modal-content">
                <div class="d-flex flex-wrap-reverse">

                    <div class="leftP w-50" style="min-height:400px ;">
                        <div class="left-cont">
                            <img src="{% static 'rsc/icons8-project-management-48.png' %}" alt="">
                            <h3>managesnap</h3>
                        </div>

                    </div>
                    <div class="rightP px-4 w-50 my-2 d-flex flex-column justify-content-center">

                        <h5 class="modal-title py-3" id="exampleModalLabel">Add link</h5>
                        <form action="{% url 'manager:announcement-add-link' announcement.pk %}" method="post">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="title">Link</label>
                                <input type="text" class="form-control w-100" id="link" name="link_url">
                            </div>
                            <div class="footer-btns mt-5">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                <button type="submit" class="btn btn-primary">Save changes</button>
                            </div>
                        </form>




                    </div>

                </div>

            </div>
        </div>
    </div>

    <!-- add file popup -->
    <div class="modal fade" id="addFile" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
            <div class="modal-content">
                <div class="d-flex flex-wrap-reverse">

                    <div class="leftP w-50" style="min-height:400px ;">
                        <div class="left-cont">
                            <img src="{% static 'rsc/icons8-project-management-48.png' %}" alt="">
                            <h3>managesnap</h3>
                        </div>

                    </div>
                    <div class="rightP px-4 w-50 my-2 d-flex flex-column justify-content-center">

                        <h5 class="modal-title py-3" id="exampleModalLabel">Add File</h5>
                        <form method="post" enctype="multipart/form-data" action="{% url 'manager:announcement-add-file' announcement.pk %}">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="file">File</label>
                                <input type="file" class="form-control w-100" id="file" name="file">
                            </div>

                            <div class="footer-btns mt-5">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                <button type="submit" class="btn btn-primary">Save changes</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endblock body %}
    {% block script %}
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
            integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
            crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
            integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
            crossorigin="anonymous"></script>
        <script src="{% static 'scripts/add-course.js' %}"></script>
        <script src="{% static 'scripts/groups-script.js' %}"></script>
        <script src="{% static 'scripts/profile-script.js' %}"></script>
        <script src="{% static 'scripts/announcements-script.js' %}"></script>
        <script src="{% static 'scripts/students-script.js' %}"></script>
    {% endblock script %}

templates/manager/student_profile_detail.html
{% extends 'manager/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}RequestDetail{% endblock title %}
{% block css %}
<link rel="stylesheet" href="{% static 'styles/students-style.css' %}">
<link rel="stylesheet" href="{% static 'styles/courses-style.css'%}">
<link rel="stylesheet" href="{% static 'styles/add-popup.css'%}">
<link rel="stylesheet" href="{% static 'styles/profile-style.css'%}">
<link rel="stylesheet" href="{% static 'css/w3.css'%}">
<style>
    p{
        margin-bottom: 0 !important;
    }
</style>
{% endblock css %}
{% block body %}
    <div class="body">
        {% include 'messages.html' %}

        <div class="prof-container">
            <div class="prof">
                <div class="prof-item prof-details">
                    <div class="image-details">
                        <div class="prof-image">
                            {% if application.profile.profile_pic %}
                                <img src="{{application.profile.profile_pic.url}}" alt="">
                            {% else %}
                                <img src="" alt="">
                            {% endif %}

                        </div>
                        <div class="details">
                            <p class="prof-name">{{ application.full_name }}</p>
                            {% if application.is_verified %}
                            <p class="status"><b>Status : </b><span>Verifed</span></p>
                            {% endif %}
                            {% if application.is_rejected %}
                            <p class="status"><b>Status : </b><span>Rejected</span></p>
                            {% endif %}
                            {% if application.is_rejected == False and application.is_verified == False%}
                            <p class="status"><b>Status : </b><span>Pending</span></p>
                            {% endif %}
                        </div>
                    </div>
                </div>
                <div class="tabs prof-item">
                    <div class="tab personal current">
                        <img src="{% static 'rsc/icons8-person-30.png' %}" alt="" class="icon">
                        <p>Personal</p>
                    </div>
                    <div class="tab education not-current">
                        <img src="{% static 'rsc/icons8-student-center-30.png' %}" alt="" class="icon">
                        <p>Education</p>
                    </div>
                    <div class="tab experience not-current">
                        <img src="{% static 'rsc/icons8-laptop-30.png' %}" alt="" class="icon">
                        <p>Experience</p>
                    </div>
                </div>
                <div class="prof-item personal-info">
                    <div class="info">
                        <img src="{% static 'rsc/icons8-iphone-24.png' %}" alt="" class="icon">
                        <p class="info-name">Mobile : </p>
                    </div>
                    <div class="info">
                        <img src="{% static 'rsc/icons8-mail-24.png' %}" alt="" class="icon">
                        <p class="info-name">Email : {{ application.profile.email }} </p>
                    </div>
                    <div class="info">
                        <img src="{% static 'rsc/icons8-location-24 (1).png' %}" alt="" class="icon">
                        <p class="info-name">Location</p>
                    </div>
                    <div class="info">
                        <img src="{% static 'rsc/icons8-visualization-skill-24.png' %}" alt="" class="icon">
                        <p class="info-name">Skills : </p>
                    </div>
                    <div class="info">
                        <img src="{% static 'rsc/icons8-linkedin-24 (1).png' %}" alt="" class="icon">
                        <p class="info-name">LinkedIn : </p>
                    </div>
                    <div class="info">
                        <img src="{% static 'rsc/icons8-github-24.png' %}" alt="" class="icon">
                        <p class="info-name">Github : </p>
                    </div>
                    <div class="info">
                        <img src="{% static 'rsc/icons8-code-24.png' %}" alt="" class="icon">
                        <p class="info-name">Programming Languages : </p>
                    </div>
                </div>
                <div class="prof-item education-info">
                    <div class="info">
                        <img src="rsc/icons8-iphone-24.png" alt="" class="icon">
                        <p class="info-name">Semester : {{ application.semester}}</p>
                    </div>
                    <div class="info">
                        <img src="rsc/icons8-mail-24.png" alt="" class="icon">
                        <p class="info-name">Section : {{ application.section}}</p>
                    </div>
                    <div class="info">
                        <img src="rsc/icons8-location-24 (1).png" alt="" class="icon">
                        <p class="info-name">Department: {{ application.department}}</p>
                    </div>
                    <div class="info">
                        <img src="{% static 'rsc/icons8-visualization-skill-24.png' %}" alt="" class="icon">
                        <p class="info-name">Skills : </p>
                    </div>
                    <div class="info">
                        <img src="{% static 'rsc/icons8-linkedin-24 (1).png' %}" alt="" class="icon">
                        <p class="info-name">LinkedIn : </p>
                    </div>
                    <div class="info">
                        <img src="{% static 'rsc/icons8-github-24.png' %}" alt="" class="icon">
                        <p class="info-name">Github : </p>
                    </div>
                    <div class="info">
                        <img src="{% static 'rsc/icons8-code-24.png' %}" alt="" class="icon">
                        <p class="info-name">Programming Languages : </p>
                    </div>
                </div>
                <div class="prof-item experience-info">
                    <div class="info">
                        <img src="{% static 'rsc/icons8-iphone-24.png' %}" alt="" class="icon">
                        <p class="info-name">Mobile : </p>
                    </div>
                    <div class="info">
                        <img src="{% static 'rsc/icons8-mail-24.png' %}" alt="" class="icon">
                        <p class="info-name">Email : </p>
                    </div>
                    <div class="info">
                        <img src="{% static 'rsc/icons8-location-24 (1).png' %}" alt="" class="icon">
                        <p class="info-name">Location</p>
                    </div>
                    <div class="info">
                        <img src="{% static 'rsc/icons8-visualization-skill-24.png' %}" alt="" class="icon">
                        <p class="info-name">Skills : </p>
                    </div>
                    <div class="info">
                        <img src="{% static 'rsc/icons8-linkedin-24 (1).png' %}" alt="" class="icon">
                        <p class="info-name">LinkedIn : </p>
                    </div>
                    <div class="info">
                        <img src="{% static 'rsc/icons8-github-24.png' %}" alt="" class="icon">
                        <p class="info-name">Github : </p>
                    </div>
                    <div class="info">
                        <img src="{% static 'rsc/icons8-code-24.png' %}" alt="" class="icon">
                        <p class="info-name">Programming Languages : </p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {% endblock body %}
    {% block script %}
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
            integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
            crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
            integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
            crossorigin="anonymous"></script>
        <script src="{% static 'scripts/add-course.js' %}"></script>
        <script src="{% static 'scripts/groups-script.js' %}"></script>
        <script src="{% static 'scripts/profile-script.js' %}"></script>
        <script src="{% static 'scripts/announcements-script.js' %}"></script>
        <script src="{% static 'scripts/students-script.js' %}"></script>
    {% endblock script %}