lms/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

admin.site.index_title = 'Unstarted Administration'
admin.site.site_header = 'Unstarted Administration'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
    path('management/', include('manager.urls')),
    path('teacher/', include('teacher.urls')),
    path('student/', include('student.urls')),
    path('payment/', include('payment.urls')),
    path('ckeditor', include('ckeditor_uploader.urls')),
]

urlpatterns += static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL , document_root = settings.STATIC_ROOT)

student/urls.py
from django.urls import path
from .views import (
    index,
    enrolled_courses,
    course_detail_view,
    course_units_view,
    allcourses,
    calender,
    communication,
    course_detail,
    course_learning,
    course_tools,
    notifications_page,
    course_content,
    assignments,
    assignments_detail,
    course_tasks,
    unit_launch
)


app_name = 'student'


urlpatterns = [
    path('', index, name='home'),
    path('courses/', enrolled_courses, name='enrolled-courses'),
    path('course/<int:course_id>/', course_detail_view, name='course-detail'),
    path('course/<int:course_id>/units/', course_units_view, name='course-units-view'),
    path('courses/allcourses',allcourses,name="allcourses"),
    path('courses/calender',calender,name="calender"),
    path('courses/communication',communication,name="communication"),
    path('courses/course_learning',course_learning,name="course_learning"),
    path('courses/course_tools',course_tools,name="course_tools"),
    path('courses/notifications_page',notifications_page,name="notifications"),
    path('courses/course_content',course_content,name="course_content"),
    path('courses/assignments',assignments,name="assignments"),
    path('courses/assignments_detail',assignments_detail,name="assignments_detail"),
    path('courses/course_tasks',course_tasks,name="course_tasks"),
    path('courses/unit_launch',unit_launch,name="unit_launch"),
]

teacher/urls.py
from django.urls import path

from .views import (
    home,
testing,
    CourseCreateView,
    CourseDetailView,
    CourseUpdateView,
    CourseDeleteView,
    CourseListView,
    CourseReleaseView,

    UnitCreateView,
    UnitDetailView,
    UnitUpdateView,
    UnitDeleteView,
    UnitListView,
    UnitReleaseView,

    LessonCreateView,
    LessonDetailView,
    LessonUpdateView,
    LessonDeleteView,
    LessonListView,
    LessonFileCreateView,
    LessonFileDeleteView,
    lesson_link_create,
    lesson_link_delete,
    LessonReleaseView,

    EnrollmentListView,
    EnrollmentCreateView,
    EnrollmentUpdateView,
    EnrollmentDeleteView,
    course_stats_view,

    GroupCreateView,
    GroupListView,
    GroupStudentListView,
    AddStudentToGroupView,
    RemoveStudentFromGroupView,
    CreateGroupCourseEnrollmentView,
    DeleteGroupCourseEnrollmentView,

    AnnouncementListView,
    AnnouncementCreateView,
    AnnouncementDetailView,
    AnnouncementUpdateView,
    AnnouncementDeleteView,
    AnnouncementFileCreateView,
    AnnouncementFileDeleteView,
    AnnouncementLinkCreateView,
    AnnouncementLinkDeleteView,
)

app_name = 'teacher'


urlpatterns = [
    path('', home, name='home'),
    # Course URLs
    path('testing',testing,name="testing"),
    path('course/create/', CourseCreateView.as_view(), name='course-create'),
    path('course/<int:pk>/', CourseDetailView.as_view(), name='course-detail'),
    path('course/<int:pk>/update/', CourseUpdateView.as_view(), name='course-update'),
    path('course/<int:pk>/delete/', CourseDeleteView.as_view(), name='course-delete'),
    path('courses/', CourseListView.as_view(), name='course-list'),
    path('course/release/<int:course_id>/', CourseReleaseView.as_view(), name='course-release'),

    # Unit URLs
    path('course/<int:course_pk>/units/create/', UnitCreateView.as_view(), name='unit-create'),
    path('units/<int:pk>/', UnitDetailView.as_view(), name='unit-detail'),
    path('units/<int:pk>/update/', UnitUpdateView.as_view(), name='unit-update'),
    path('course/<int:course_id>/units/<int:pk>/delete/', UnitDeleteView.as_view(), name='unit-delete'),
    path('course/<int:course_pk>/units/', UnitListView.as_view(), name='unit-list'),
    path('unit/<int:unit_id>/release/', UnitReleaseView.as_view(), name='unit-release'),

    # Lesson URLs
    path('units/<int:unit_pk>/lessons/create/', LessonCreateView.as_view(), name='lesson-create'),
    path('courses/<int:course_id>/lessons/<int:pk>/', LessonDetailView.as_view(), name='lesson-detail'),
    path('lessons/<int:pk>/update/', LessonUpdateView.as_view(), name='lesson-update'),
    path('course/<int:unit_id>/lessons/<int:pk>/delete/', LessonDeleteView.as_view(), name='lesson-delete'),
    path('courses/<int:course_id>/units/<int:unit_pk>/lessons/', LessonListView.as_view(), name='lesson-list'),
    path('lesson/<int:lesson_id>/release/', LessonReleaseView.as_view(), name='lesson-release'),

    # LessonFile URLs
    path('lessons/<int:lesson_pk>/files/create/', LessonFileCreateView.as_view(), name='lesson-file-create'),
    path('lesson-files/<int:pk>/delete/', LessonFileDeleteView.as_view(), name='lesson-file-delete'),

    # LessonLink URLs
    path('lessons/<int:lesson_pk>/links/create/', lesson_link_create, name='lesson-link-create'),
    path('lesson-links/<int:pk>/delete/', lesson_link_delete, name='lesson-link-delete'),

    #FOr student stats and enrollments
    path('course/<int:course_id>/enrollment/', EnrollmentListView.as_view(), name='enrollment-list'),
    path('enrollment/create/<int:course_id>/<int:student_id>/', EnrollmentCreateView.as_view(), name='enrollment-create'),
    path('course/<int:course_id>/enrollment/<int:pk>/update/', EnrollmentUpdateView.as_view(), name='enrollment-update'),
    path('enrollment/<int:course_id>/<int:enrollment_id>/delete/', EnrollmentDeleteView.as_view(), name='enrollment-delete'),
    path('course/<int:course_id>/stats/', course_stats_view, name='course-stats'),

    ## groups
    path('groups/create/', GroupCreateView.as_view(), name='group-create'),
    path('groups/', GroupListView.as_view(), name='group-list'),
    path('groups/<int:group_id>/students/', GroupStudentListView.as_view(), name='group-student-list'),
    path('groups/<int:group_id>/add-student/', AddStudentToGroupView.as_view(), name='group-add-student'),
    path('groups/<int:group_id>/remove-student/<int:pk>/', RemoveStudentFromGroupView.as_view(), name='group-remove-student'),


    ##group course enrollments
    path('group/<int:group_id>/course/<int:course_id>/enroll/', CreateGroupCourseEnrollmentView.as_view(), name='group-course-enroll'),
    path('group/<int:group_id>/course/<int:course_id>/enroll/delete/', DeleteGroupCourseEnrollmentView.as_view(), name='group-course-enrollment-delete'),

    ## announcements
    path('course/<int:course_pk>/announcements/', AnnouncementListView.as_view(), name='announcement-list'),
    path('course/<int:course_pk>/announcements/create/', AnnouncementCreateView.as_view(), name='announcement-create'),
    path('announcement/<int:pk>/', AnnouncementDetailView.as_view(), name='announcement-detail'),
    path('announcement/<int:pk>/update/', AnnouncementUpdateView.as_view(), name='announcement-update'),
    path('announcement/<int:pk>/delete/', AnnouncementDeleteView.as_view(), name='announcement-delete'),
    path('announcement/<int:announcement_pk>/files/create/', AnnouncementFileCreateView.as_view(), name='announcement-file-create'),
    path('announcement/files/<int:pk>/delete/', AnnouncementFileDeleteView.as_view(), name='announcement-file-delete'),
    path('announcement/<int:announcement_pk>/links/create/', AnnouncementLinkCreateView.as_view(), name='announcement-link-create'),
    path('announcement/links/<int:pk>/delete/', AnnouncementLinkDeleteView.as_view(), name='announcement-link-delete'),


]

student/models.py
from django.db import models

# Create your models here.

student/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from teacher.models import (
    Enrollment,
    Course,
    LessonProgress,
)
from django.utils import timezone

@login_required
def enrolled_courses(request):
    enrolled_courses = Enrollment.objects.filter(student=request.user).select_related('course')
    return render(request, 'student/enrolled_courses.html', {'enrolled_courses': enrolled_courses})


@login_required
def course_detail_view(request, course_id):
    course = get_object_or_404(Course, pk=course_id)
    student = request.user
    enrollment = Enrollment.objects.filter(student=student, course=course).first()
    # Update the last_accessed field to the current timestamp
    enrollment.last_accessed = timezone.now()
    enrollment.save()
    units = course.unit_set.all()

    unit_progress = []
    for unit in units:
        lessons_total = unit.lesson_set.count()
        lessons_completed = LessonProgress.objects.filter(enrollment=enrollment, lesson__unit=unit, is_completed=True).count()
        completion_percentage = (lessons_completed / lessons_total) * 100 if lessons_total > 0 else 0
        unit_progress.append((unit, completion_percentage, lessons_completed, lessons_total))

    context = {
        'course': course,
        'enrollment': enrollment,
        'unit_progress': unit_progress,
    }

    return render(request, 'student/course_detail.html', context)



def course_units_view(request, course_id):
    course = get_object_or_404(Course, pk=course_id)
    units = course.unit_set.all()

    for unit in units:
        unit.lessons = unit.lesson_set.all()

    context = {
        'course': course,
        'units': units,
    }

    return render(request, 'student/course_learning_page.html', context)


def index(request):
    total_course_enrollments = Enrollment.objects.filter(student=request.user).select_related('course').order_by('-last_accessed')
    recently_accessed_course_enrollments = total_course_enrollments[:6]
    total_course_enrollments_count = total_course_enrollments.count()

    context = {
        'recently_accessed_course_enrollments' : recently_accessed_course_enrollments,
        'total_course_enrollments_count' : total_course_enrollments_count
    }
    return render(request, 'student/index.html', context)


def allcourses(request):
    return render(request,'student/enrolled_courses.html')

def calender(request):
    return render(request,'student/calender_page.html')

def communication(request):
    return render(request,'student/communication_page.html')

def course_detail(request):
    return render(request,'student/course_detail.html')

def course_learning(request):
    return render(request,'student/course_learning_page.html')

def course_tools(request):
    return render(request,'student/course_tools_page.html')

def notifications_page(request):
    return render(request,'student/notifications_page.html')

def course_content(request):
    return render(request,'student/course_learning_page.html')

def assignments(request):
    return render(request,'student/assignments.html')

def assignments_detail(request):
    return render(request,'student/assignments_detail.html')

def course_tasks(request):
    return render(request,'student/course_tasks.html')

def unit_launch(request):
    return render(request,'student/unit_launch.html')

templates/teacher/course.html
{% extends 'teacher/course_base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}coursedetail{% endblock title %}
{% block css %}
<link rel="stylesheet" href="{% static "styles/courses-style.css"%}">
<link rel="stylesheet" href="{% static "styles/add-popup.css"%}">
{% endblock css %}
{% block body %}
<div class="add-course">
    <div class="popup">
        <div class="left">
            <div class="left-cont">
                <img src="{% static 'rsc/icons8-project-management-48.png' %}" alt="">
                <h3>managesnap</h3>
            </div>
        </div>
        <form method="POST" action="{% url 'teacher:course-update' course.id %}" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="right">
                <div class="right-cont">
                    <div class="right-item">
                        <h3>Course Title</h3>
                        <input type="text" name="title" placeholder="Enter course title" value="{{ course.title }}" required>
                    </div>
                    <div class="right-item">
                        <h3>Banner Image</h3>
                        <input type="file" name="image" accept="image/*">
                    </div>
                    <div class="right-item">
                        <h3>Course Price</h3>
                        <input type="number" name="course_price" placeholder="Enter course price" value="{{ course.course_price }}" required>
                    </div>
                    <div class="right-item">
                        <h3>Is Paid?</h3>
                        <input type="checkbox" name="is_paid" {% if course.is_paid %}checked{% endif %}>
                    </div>
                    <div class="right-item">
                        <h3>Course Level</h3>
                        <select name="course_level">
                            <option value="Beginner" {% if course.course_level == 'Beginner' %}selected{% endif %}>Beginner</option>
                            <option value="Intermediate" {% if course.course_level == 'Intermediate' %}selected{% endif %}>Intermediate</option>
                            <option value="Advanced" {% if course.course_level == 'Advanced' %}selected{% endif %}>Advanced</option>
                        </select>
                    </div>
                    <div class="right-item ac-btn">
                        <button class="a" type="submit">Update</button>
                        <button class="cancel">Cancel</button>
                    </div>
                </div>
            </div>
        </form>
        <img src="{% static 'rsc/icons8-close-50.png' %}" alt="" class="cancel-icon">
    </div>
</div>


    <div class="body">
        <div class="courses-container">
            <div class="courses-heading course-item">
                <p class="main">coursedetails</p>
            </div>
            <div class="courses course-item">
                <div class="course-sets">

                    <div class="course" style="width:auto;">
                        <div class="course-banner">
                            <img src="{{ course.image.url }}" alt="" class="banner">
                        </div>
                        <div class="course-details">
                            <div class="course-author cd">
                                {% if course.created_by.profile.profile_pic %}
                                <img src="{{ course.created_by.profile.profile_pic.url }}" alt="" class="author">
                                {% else %}
                                <img src="{% static 'rsc/author-1' %}" alt="" class="author">
                                {% endif %}
                                <p>{{ course.created_by.username }}</p>
                            </div>
                            <h3 class="course-name cd">{{ course.title }}</h3>
                            <div class="diff-preview cd">
                                <div class="difficulty">
                                    <p>{{ course.course_level }}</p>
                                </div>
                                <div class="preview">
                                {% if has_released_lessons %}
                                <form method="POST" action="{% url 'teacher:course-release' course.id %}">
                                    {% csrf_token %}
                                    {% if course.is_released %}
                                    <button type="submit" class="preview-btn">Draft</button>
                                    {% else %}
                                    <button type="submit" class="preview-btn">Release</button>
                                    {% endif %}
                                </form>
                                {% endif %}
                                </div>

                            </div>
                            <div class="diff-preview">
                                <div class="cd">
                                <button class="filter-btn" id="add-course-btn">edit</button>
                                </div>
                                <div class="cd">
                                    <a href="{% url 'teacher:enrollment-list' course.id %}">
                                        <button class="filter-btn">Enroll Students</button>
                                    </a>
                                </div>
                                <div class=" cd">
                                    <a href="{% url 'teacher:course-stats' course.id %}">
                                        <button class="filter-btn">Student stats</button>
                                    </a>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>



    </div>
    {% endblock body %}


    {% block script %}
</div>
<script src="{% static "scripts/coursearrow.js"%}"></script>
<script src="{% static 'scripts/add-course.js' %}"></script>
    {% endblock script %}

templates/teacher/courses.html
{% extends 'teacher/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Allcourses{% endblock title %}
{% block css %}
<link rel="stylesheet" href="{% static 'styles/courses-style.css'%}">
<link rel="stylesheet" href="{% static 'styles/add-popup.css'%}">
{% endblock css %}
{% block body %}
<div class="add-course">
    <div class="popup">
        <div class="left">
            <div class="left-cont">
                <img src="{% static 'rsc/icons8-project-management-48.png' %}" alt="">
                <h3>managesnap</h3>
            </div>
        </div>
        <form method="POST" action="{% url 'teacher:course-create' %}" enctype="multipart/form-data">
            {% csrf_token %}
        <div class="right">
            <div class="right-cont">
                <div class="right-item">
                    <h3>Course Title</h3>
                    <input type="text" name="title" placeholder="Enter course title" required>
                </div>
                <div class="right-item">
                    <h3>Banner Image</h3>
                    <input type="file" name="image" accept="image/*">
                </div>
                <div class="right-item">
                    <h3>Course Price</h3>
                    <input type="number" name="course_price" placeholder="Enter course price" required>
                </div>
                <div class="right-item">
                    <h3>Is Paid?</h3>
                    <input type="checkbox" name="is_paid">
                </div>
                <div class="right-item">
                    <h3>Course Level</h3>
                    <select name="course_level">
                        <option value="Beginner">Beginner</option>
                        <option value="Intermediate">Intermediate</option>
                        <option value="Advanced">Advanced</option>
                    </select>
                </div>
                <div class="right-item ac-btn">
                    <button class="testing" type="submit">Create</button>
                    <button class="cancel">Cancel</button>
                </div>
            </div>
        </div>
    </form>
        <img src="{% static 'rsc/icons8-close-50.png' %}" alt="" class="cancel-icon">
    </div>
</div>

    <div class="body">
        <div class="courses-container">
            <div class="courses-heading course-item">
                <p class="main">Explore Courses</p>
            </div>
            <div class="filter-search course-item">
                <div class="search fs-item">
                    <input type="text" name="" id="" placeholder="search courses" class="search-item searchbar">
                    <img src="{% static 'rsc/icons8-search-50 (4).png' %}" alt="" class="search-icon search-item">
                </div>
                <div class="filter fs-item">
                    <button class="filter-btn" id="add-course-btn">Add</button>
                </div>
            </div>
            <div class="courses course-item">
                <div class="course-sets">
                    {% for course in courses %}
                    <div class="course">
                        <div class="course-banner">
                            <img src="{{ course.image.url }}" alt="" class="banner">
                        </div>
                        <div class="course-details">
                            <div class="course-author cd">
                                {% if course.created_by.profile.profile_pic %}
                                <img src="{{ course.created_by.profile.profile_pic.url }}" alt="" class="author">
                                {% else %}
                                <img src="{% static 'rsc/author-1' %}" alt="" class="author">
                                {% endif %}
                                <p>{{ course.created_by.username }}</p>
                            </div>
                            <h3 class="course-name cd">{{ course.title }}</h3>
                            <div class="diff-preview cd">
                                <div class="difficulty">
                                    <p>{{ course.course_level }}</p>
                                </div>
                                <div class="preview">
                                    <a href="{% url 'teacher:course-detail' course.pk %}"><button class="preview-btn">Preview</button></a>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% empty %}
                    No courses
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>

    <script src="{% static 'scripts/add-course.js' %}"></script>
    {% endblock body %}

templates/teacher/lessons.html
{% extends 'teacher/course_base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}lessons{% endblock title %}
{% block css %}
<link rel="stylesheet" href="{% static 'styles/announcements-style.css'%}">
<link rel="stylesheet" href="{% static 'styles/add-popup.css'%}">
{% endblock css %}
{% block body %}
<div class="add-course">
    <div class="popup">
        <div class="left">
            <div class="left-cont">
                <img src="{% static 'rsc/icons8-project-management-48.png' %}" alt="">
                <h3>managesnap</h3>
            </div>
        </div>
        <form method="POST" action="{% url 'teacher:lesson-create' unit.id %}" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="right">
                <div class="right-cont">
                    <div class="right-item">
                        <h3>Lesson Title</h3>
                        <input type="text" name="title" placeholder="Enter unit title" required>
                    </div>
                    <div class="right-item">
                        <h3>Description</h3>
                        <textarea name="description" placeholder="Enter unit description" required></textarea>
                    </div>
                    <div class="right-item">
                        <h3>Due Date</h3>
                        <input type="date" name="due_date" required>
                    </div>
                    <div class="right-item ac-btn">
                        <button type="submit">Create</button>
                        <button class="cancel">Cancel</button>
                    </div>
                </div>
            </div>
        </form>
        <img src="{% static 'rsc/icons8-close-50.png' %}" alt="" class="cancel-icon">
    </div>
</div>

    <div class="body">
        <div class="announcements-container">
            <div class="ann">
                <div class="heading ann-item">
                    <div class="head heading-item">
                        <p class="heading-name">
                            {{unit.title}}
                        </p>
                    </div>
                    <div class="add-search ann-item heading-item">
                        <div class="search as-item">
                            <input type="text" name="" id="" placeholder="search" class="search-item searchbar">
                            <img src="{% static 'rsc/icons8-search-50 (4).png' %}" alt="" class="search-icon search-item">
                        </div>
                        <div class="add as-item">
                            <button class="add-btn" id="add-course-btn"><p>Add</p></button>
                        </div>
                        <div>
                            <button class="add-btn"><p>Edit</p></button>
                        </div>
                        <div>
                            {% if has_released_lessons %}
                            <form method="POST" action="{% url 'teacher:unit-release' unit.id %}">
                                {% csrf_token %}
                            {% if unit.is_released %}
                            <button class="add-btn" type="submit"><p>Draft</p></button>
                            {% else %}
                            <button type="submit" class="add-btn"><p>Release</p></button>
                            {% endif %}
                            </form>
                            {% endif %}
                        </div>
                    </div>
                </div>

                <div class="tabs ann-item">
                    <div class="tab rel current">
                        <img src="{% static 'rsc/icons8-sent-50.png' %}" alt="" class="icon">
                        <p>Released</p>
                    </div>
                    <div class="tab dra not-current">
                        <img src="{% static 'rsc/icons8-draft-48.png' %}" alt="" class="icon">
                        <p>Drafts</p>
                    </div>
                </div>
                <div class="ann-item released-container">
                    {% for lesson in released_lessons %}
                    <div class="released">
                        <div class="ann-content">
                            <h3 class="ann-heading rd-item">{{ lesson.title }}</h3>
                            <p class="ann-para rd-item">{{ lesson.description }}</p>
                            <div class="ann-links-docs rd-item">
                                <div class="links">
                                    <img src="{% static 'rsc/icons8-link-24 (1).png' %}" alt="" class="icon">
                                    <p class="link-num">Links : {{ lesson.lessonlink_count }}</p>
                                </div>
                                <div class="docs">
                                    <img src="{% static 'rsc/icons8-documents-24.png' %}" alt="" class="icon">
                                    <p class="docs-num">Documents : {{ lesson.lessonfiles_count }}</p>
                                </div>
                            </div>
                        </div>
                        <div class="ann-buttons">
                            <button class="view"><a href="{% url 'teacher:lesson-detail' course_id=course.id pk=lesson.pk %}">View</a></button>

                            <form method="POST" action="{% url 'teacher:lesson-delete' unit_id=unit.id pk=lesson.pk %}">
                                {% csrf_token %}
                                <button type="submit" class="edit">Delete</button>
                            </form>
                        </div>
                    </div>
                    {% empty %}
                    No released lessons
                    {% endfor %}


                </div>
                <div class="ann-item drafts-container">
                    {% for lesson in draft_lessons %}
                    <div class="drafts">
                        <div class="ann-content">
                            <h3 class="ann-heading rd-item">{{ lesson.title }}</h3>
                            <p class="ann-para rd-item">{{ lesson.description }}</p>
                            <div class="ann-links-docs rd-item">
                                <div class="links">
                                    <img src="{% static 'rsc/icons8-link-24 (1).png' %}" alt="" class="icon">
                                    <p class="link-num">Links : {{ lesson.lessonlink_count }}</p>
                                </div>
                                <div class="docs">
                                    <img src="{% static 'rsc/icons8-documents-24.png' %}" alt="" class="icon">
                                    <p class="docs-num">Documents : {{ lesson.lessonfile_count }}</p>
                                </div>
                            </div>
                        </div>
                        <div class="ann-buttons">
                            <button class="view"><a href="{% url 'teacher:lesson-detail' course_id=course.id pk=lesson.pk %}">View</a></button>
                            <form method="POST" action="{% url 'teacher:lesson-delete' unit_id=unit.id pk=lesson.pk %}">
                                {% csrf_token %}
                                <button type="submit" class="edit">Delete</button>
                            </form>
                        </div>
                    </div>
                    {% empty %}
                    No drafted lessons
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    <script src="{% static 'scripts/add-course.js' %}"></script>
    <script src="{% static 'scripts/announcements-script.js' %}"></script>
    <script src="{% static 'scripts/coursearrow.js' %}"></script>

    {% endblock body %}